### PR TITLE
fix: spend-limit failed to compile

### PR DESCRIPTION
**Pull request by phureewat29**
# What :computer:

The `spend-limit` has failed to compile after PR #31 to replace `zksync-web3` with `zksync-ethers@5`. 
It caused the following error when running the hardhat compile.

```
❯ yarn hardhat compile
An unexpected error occurred:

Error: Cannot find module 'zksync-web3'
Require stack:
- /tutorials/spend-limit/node_modules/@matterlabs/hardhat-zksync-chai-matchers/dist/src/internal/changeEtherBalance.js
- /tutorials/spend-limit/node_modules/@matterlabs/hardhat-zksync-chai-matchers/dist/src/internal/hardhatChaiMatchers.js
- /tutorials/spend-limit/node_modules/@matterlabs/hardhat-zksync-chai-matchers/dist/src/internal/add-chai-matchers.js
- /tutorials/spend-limit/node_modules/@matterlabs/hardhat-zksync-chai-matchers/dist/src/index.js
- /tutorials/spend-limit/hardhat.config.ts
- /tutorials/node_modules/hardhat/internal/core/config/config-loading.js
- /tutorials/node_modules/hardhat/internal/cli/cli.js
- /tutorials/node_modules/hardhat/internal/cli/bootstrap.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/tutorials/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/tutorials/spend-limit/node_modules/@matterlabs/hardhat-zksync-chai-matchers/src/internal/changeEtherBalance.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.require.extensions.<computed> [as .js] (/tutorials/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1207:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tutorials/spend-limit/node_modules/@matterlabs/hardhat-zksync-chai-matchers/dist/src/internal/changeEtherBalance.js',
    '/tutorials/spend-limit/node_modules/@matterlabs/hardhat-zksync-chai-matchers/dist/src/internal/hardhatChaiMatchers.js',
    '/tutorials/spend-limit/node_modules/@matterlabs/hardhat-zksync-chai-matchers/dist/src/internal/add-chai-matchers.js',
    '/tutorials/spend-limit/node_modules/@matterlabs/hardhat-zksync-chai-matchers/dist/src/index.js',
    '/tutorials/spend-limit/hardhat.config.ts',
    '/tutorials/node_modules/hardhat/internal/core/config/config-loading.js',
    '/tutorials/node_modules/hardhat/internal/cli/cli.js',
    '/tutorials/node_modules/hardhat/internal/cli/bootstrap.js'
  ]
}
```

# Why :hand:

This PR is to fix the above error by upgrading the `@matterlabs/hardhat-zksync-chai-matchers` to `0.2.1` (currently is 0.1.3) so we can get rid of the `zksync-web3` dependency from this codebase.

Moreover, this PR includes some `chore` work to make the code more consistency and prevent human errors of compromising their private key in git.

# Evidence :camera:

The hardhat compile command will succeed as expected.

```
❯ yarn hardhat compile
Compiling contracts for zkSync Era with zksolc v1.4.0 and solc v0.8.17
Compiling 34 Solidity files

Successfully compiled 34 Solidity files
```

# Notes :memo:

N/A

### CODE REVIEW

**Comment by uF4No** [comment]
This will be fixed in #41
